// <auto-generated>
// Code generated by LUISGen C:\Users\shrey\Downloads\DMaaS-01.json -cs Luis.FilesMain -o C:\Users\shrey\Downloads
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;

namespace CoreBot2.CognitiveModels
{
    public partial class FilesMain: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            Appreciation, 
            Bad_Mood, 
            Bot_Definition, 
            Bot_name, 
            BotHelp, 
            Data_transfer, 
            File_Status, 
            GDW_Queue, 
            Good_Mood, 
            Market_Health_Status, 
            McD_Abbreviations, 
            Misc, 
            None, 
            Nothing, 
            Outbound_Directory, 
            Pending_files, 
            Receive_files, 
            Salutation
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Application_Owners;

            public string[] File_System_Information;

            public string[] Market_Managers;

            public string[] Support_Team;

            public string[] Vendors;

            // Instance
            public class _Instance
            {
                public InstanceData[] Application_Owners;
                public InstanceData[] File_System_Information;
                public InstanceData[] Market_Managers;
                public InstanceData[] Support_Team;
                public InstanceData[] Vendors;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<FilesMain>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
